(* Content-type: application/vnd.wolfram.mathematica *)

(*** Wolfram Notebook File ***)
(* http://www.wolfram.com/nb *)

(* CreatedBy='Mathematica 11.2' *)

(*CacheID: 234*)
(* Internal cache information:
NotebookFileLineBreakTest
NotebookFileLineBreakTest
NotebookDataPosition[       158,          7]
NotebookDataLength[     33888,        999]
NotebookOptionsPosition[     33584,        986]
NotebookOutlinePosition[     33932,       1001]
CellTagsIndexPosition[     33889,        998]
WindowFrame->Normal*)

(* Beginning of Notebook Content *)
Notebook[{
Cell[BoxData[
 RowBox[{
  RowBox[{"(*", "1", "*)"}], "\n", 
  RowBox[{"(*", 
   RowBox[{"Am", "-", "241"}], "*)"}], "\n", 
  RowBox[{
   RowBox[{
    RowBox[{"isotopeName", "=", "\"\<Am-241\>\""}], ";"}], "\n", 
   RowBox[{
    RowBox[{"databaseName", "=", "\"\<JENDL-5\>\""}], ";"}], "\n", "\n", 
   RowBox[{
    RowBox[{"atomicNumber", "=", "95"}], ";", 
    RowBox[{"(*", 
     RowBox[{"Atomic", " ", "number"}], "*)"}], "\n", 
    RowBox[{"neutronNumber", "=", "147"}], ";", 
    RowBox[{"(*", 
     RowBox[{"Compound", " ", "nucleus", " ", "neutron", " ", "number"}], 
     "*)"}], 
    RowBox[{"(*", 
     RowBox[{"Calculation", " ", "Data", " ", "Range"}], "*)"}], "\n", 
    "\[IndentingNewLine]", 
    RowBox[{"energyPattern", "=", "3"}], ";", 
    RowBox[{"(*", 
     RowBox[{"Input", " ", "required"}], "*)"}], "\n", 
    RowBox[{"(*", 
     RowBox[{
      RowBox[{"energyPattern", "=", "1"}], ";", 
      RowBox[{"Data", " ", "at", " ", "0.0253", "eV"}]}], "*)"}], "\n", 
    RowBox[{"(*", 
     RowBox[{
      RowBox[{
       RowBox[{"energyPattern", "=", "2"}], ";", 
       RowBox[{"Data", " ", "at", " ", "0.0253", "eV"}]}], ",", 
      RowBox[{"500", "keV"}]}], "*)"}], "\n", 
    RowBox[{"(*", 
     RowBox[{
      RowBox[{
       RowBox[{"energyPattern", "=", "3"}], ";", 
       RowBox[{"Data", " ", "at", " ", "0.0253", "eV"}]}], ",", 
      RowBox[{"500", "keV"}], ",", 
      RowBox[{"14", "MeV"}]}], "*)"}], "\n", 
    RowBox[{"(*", 
     RowBox[{
      RowBox[{"energyPattern", "=", "4"}], ";", 
      RowBox[{"Data", " ", "at", " ", "500", "keV"}]}], "*)"}], 
    "\[IndentingNewLine]", "\[IndentingNewLine]", 
    RowBox[{"(*", 
     RowBox[{
     "Average", " ", "Number", " ", "of", " ", "Prompt", " ", "Neutrons"}], 
     "*)"}], "\n", 
    RowBox[{"promptNeutrons1", "=", "3.209"}], ";", 
    RowBox[{"(*", 
     RowBox[{"0.0253", " ", "eV"}], "*)"}], "\n", 
    RowBox[{"promptNeutrons2", "=", "3.453"}], ";", 
    RowBox[{"(*", 
     RowBox[{"500", " ", "keV", " ", "2"}], "*)"}], "\n", 
    RowBox[{"promptNeutrons3", "=", "4.972"}], ";", 
    RowBox[{"(*", 
     RowBox[{"14", " ", "MeV", " ", "4"}], "*)"}], "\n", "\n", 
    RowBox[{"(*", 
     RowBox[{"Neutron", " ", "Separation", " ", "Energy"}], "*)"}], "\n", 
    RowBox[{"neutronSeparationEnergy", "=", 
     RowBox[{"6545.5", "/", "1000"}]}], ";"}], "\n", "\n", 
   RowBox[{"(*", 
    RowBox[{
     RowBox[{
     "Charge", " ", "Distribution", " ", "Experimental", " ", "Data", " ", 
      "JENDL"}], "-", "5"}], "*)"}], "\n", 
   RowBox[{
    RowBox[{"yieldData0253eV", "=", 
     RowBox[{"{", 
      RowBox[{
       RowBox[{"{", 
        RowBox[{"23", ",", "0"}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"24", ",", 
         RowBox[{"3.675815000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "15"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"25", ",", 
         RowBox[{"4.488553000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "12"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"26", ",", 
         RowBox[{"4.081464600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "10"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"27", ",", 
         RowBox[{"6.321224500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "09"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"28", ",", 
         RowBox[{"5.813700300000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "08"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"29", ",", 
         RowBox[{"5.396068000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "07"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"30", ",", 
         RowBox[{"7.891650600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "06"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"31", ",", 
         RowBox[{"9.080356800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "05"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"32", ",", 
         RowBox[{"4.962374900000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "04"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"33", ",", 
         RowBox[{"2.458805900000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"34", ",", 
         RowBox[{"7.395102100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"35", ",", 
         RowBox[{"1.567000600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"36", ",", 
         RowBox[{"2.917890500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"37", ",", 
         RowBox[{"5.018802000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"38", ",", 
         RowBox[{"8.080385400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"39", ",", 
         RowBox[{"1.171875200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"40", ",", 
         RowBox[{"1.473843700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"41", ",", 
         RowBox[{"1.556635300000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"42", ",", 
         RowBox[{"1.586219700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"43", ",", 
         RowBox[{"1.326595700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"44", ",", 
         RowBox[{"7.209529600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"45", ",", 
         RowBox[{"2.721916000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"46", ",", 
         RowBox[{"1.945622200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"47", ",", 
         RowBox[{"5.571093200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "04"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"48", ",", 
         RowBox[{"5.638052600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "04"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"49", ",", 
         RowBox[{"3.313644000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"50", ",", 
         RowBox[{"3.481391700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"51", ",", 
         RowBox[{"7.270859400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"52", ",", 
         RowBox[{"1.263897600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"53", ",", 
         RowBox[{"1.583465500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"54", ",", 
         RowBox[{"1.749424200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"55", ",", 
         RowBox[{"1.417760800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"56", ",", 
         RowBox[{"1.074946700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"57", ",", 
         RowBox[{"7.668888600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"58", ",", 
         RowBox[{"4.851934700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"59", ",", 
         RowBox[{"2.871981200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"60", ",", 
         RowBox[{"1.517342400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"61", ",", 
         RowBox[{"6.988924600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"62", ",", 
         RowBox[{"2.804647000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"63", ",", 
         RowBox[{"9.247789400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "04"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"64", ",", 
         RowBox[{"1.901645000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "04"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"65", ",", 
         RowBox[{"1.590534400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "05"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"66", ",", 
         RowBox[{"7.722287300000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "07"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"67", ",", 
         RowBox[{"6.769845800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "08"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"68", ",", 
         RowBox[{"3.719226200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "09"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"69", ",", 
         RowBox[{"6.171167700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "11"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"70", ",", 
         RowBox[{"1.550346500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "13"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"71", ",", 
         RowBox[{"6.267620000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "17"}], ")"}]}]}]}], "}"}]}], "}"}]}], ";"}], 
   "\[IndentingNewLine]", "\[IndentingNewLine]", "\[IndentingNewLine]", 
   RowBox[{
    RowBox[{"yieldData500keV", "=", 
     RowBox[{"{", 
      RowBox[{
       RowBox[{"{", 
        RowBox[{"23", ",", 
         RowBox[{"6.946760000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "19"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"24", ",", 
         RowBox[{"1.834440400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "14"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"25", ",", 
         RowBox[{"2.460227800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "11"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"26", ",", 
         RowBox[{"2.528813100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "09"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"27", ",", 
         RowBox[{"4.200898500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "08"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"28", ",", 
         RowBox[{"3.549482900000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "07"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"29", ",", 
         RowBox[{"3.547372500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "06"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"30", ",", 
         RowBox[{"3.038959200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "05"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"31", ",", 
         RowBox[{"2.349547400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "04"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"32", ",", 
         RowBox[{"1.102012600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"33", ",", 
         RowBox[{"3.834712700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"34", ",", 
         RowBox[{"9.782982100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"35", ",", 
         RowBox[{"2.032781600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"36", ",", 
         RowBox[{"3.507650500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"37", ",", 
         RowBox[{"5.739937800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"38", ",", 
         RowBox[{"8.351386600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"39", ",", 
         RowBox[{"1.128813700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"40", ",", 
         RowBox[{"1.411021700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"41", ",", 
         RowBox[{"1.568796100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"42", ",", 
         RowBox[{"1.494090000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"43", ",", 
         RowBox[{"1.198071500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"44", ",", 
         RowBox[{"6.961135900000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"45", ",", 
         RowBox[{"3.156931100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"46", ",", 
         RowBox[{"4.072561100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"47", ",", 
         RowBox[{"1.734958400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"48", ",", 
         RowBox[{"1.759574400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"49", ",", 
         RowBox[{"3.701810400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"50", ",", 
         RowBox[{"3.016402100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"51", ",", 
         RowBox[{"6.887183700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"52", ",", 
         RowBox[{"1.312029000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"53", ",", 
         RowBox[{"1.456747400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"54", ",", 
         RowBox[{"1.561370300000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"55", ",", 
         RowBox[{"1.431329800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"56", ",", 
         RowBox[{"1.136638400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"57", ",", 
         RowBox[{"8.393280200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"58", ",", 
         RowBox[{"5.567900800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"59", ",", 
         RowBox[{"3.344336600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"60", ",", 
         RowBox[{"1.880856900000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"61", ",", 
         RowBox[{"9.597700000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"62", ",", 
         RowBox[{"3.940113800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"63", ",", 
         RowBox[{"1.503410400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"64", ",", 
         RowBox[{"3.666937600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "04"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"65", ",", 
         RowBox[{"4.282209200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "05"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"66", ",", 
         RowBox[{"3.236272100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "06"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"67", ",", 
         RowBox[{"3.278772500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "07"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"68", ",", 
         RowBox[{"3.833803100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "08"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"69", ",", 
         RowBox[{"1.511289400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "09"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"70", ",", 
         RowBox[{"6.539669900000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "12"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"71", ",", 
         RowBox[{"3.545740000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "15"}], ")"}]}]}]}], "}"}]}], "}"}]}], ";"}], 
   "\[IndentingNewLine]", "\[IndentingNewLine]", "\n", 
   RowBox[{
    RowBox[{"yieldData14MeV", "=", 
     RowBox[{"{", 
      RowBox[{
       RowBox[{"{", 
        RowBox[{"23", ",", 
         RowBox[{"1.547030000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "13"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"24", ",", 
         RowBox[{"2.676537700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "10"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"25", ",", 
         RowBox[{"5.495249300000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "08"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"26", ",", 
         RowBox[{"1.807109000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "06"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"27", ",", 
         RowBox[{"1.393543800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "05"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"28", ",", 
         RowBox[{"6.184743500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "05"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"29", ",", 
         RowBox[{"2.140598400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "04"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"30", ",", 
         RowBox[{"5.967192700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "04"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"31", ",", 
         RowBox[{"1.524710700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"32", ",", 
         RowBox[{"3.736250900000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"33", ",", 
         RowBox[{"8.420609000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"34", ",", 
         RowBox[{"1.535350500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"35", ",", 
         RowBox[{"2.442769100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"36", ",", 
         RowBox[{"3.539749300000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"37", ",", 
         RowBox[{"4.904847100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"38", ",", 
         RowBox[{"6.323370000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"39", ",", 
         RowBox[{"8.112650800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"40", ",", 
         RowBox[{"1.015271800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"41", ",", 
         RowBox[{"1.177209200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"42", ",", 
         RowBox[{"1.213364000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"43", ",", 
         RowBox[{"1.095741300000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"44", ",", 
         RowBox[{"9.798150600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"45", ",", 
         RowBox[{"8.742407200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"46", ",", 
         RowBox[{"4.793578000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"47", ",", 
         RowBox[{"2.643196300000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"48", ",", 
         RowBox[{"2.900268400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"49", ",", 
         RowBox[{"6.106390200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"50", ",", 
         RowBox[{"8.975632200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"51", ",", 
         RowBox[{"1.042513600000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"52", ",", 
         RowBox[{"9.793360200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"53", ",", 
         RowBox[{"1.169071300000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"54", ",", 
         RowBox[{"1.244258800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"55", ",", 
         RowBox[{"1.082377500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "01"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"56", ",", 
         RowBox[{"8.036932100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"57", ",", 
         RowBox[{"6.190437100000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"58", ",", 
         RowBox[{"4.725144500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"59", ",", 
         RowBox[{"3.444891900000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"60", ",", 
         RowBox[{"2.336111900000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"61", ",", 
         RowBox[{"1.437209000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "02"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"62", ",", 
         RowBox[{"7.356261500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"63", ",", 
         RowBox[{"3.699951900000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"64", ",", 
         RowBox[{"1.706876300000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "03"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"65", ",", 
         RowBox[{"5.787499800000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "04"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"66", ",", 
         RowBox[{"2.014623200000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "04"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"67", ",", 
         RowBox[{"6.176046700000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "05"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"68", ",", 
         RowBox[{"1.852469500000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "05"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"69", ",", 
         RowBox[{"2.862408900000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "06"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"70", ",", 
         RowBox[{"1.134697400000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "07"}], ")"}]}]}]}], "}"}], ",", 
       RowBox[{"{", 
        RowBox[{"71", ",", 
         RowBox[{"6.385320000000", "*", 
          RowBox[{"10", "^", 
           RowBox[{"(", 
            RowBox[{"-", "10"}], ")"}]}]}]}], "}"}]}], "}"}]}], ";"}], 
   "\[IndentingNewLine]", "\n", "\n", "\n"}]}]], "Input",
 CellChangeTimes->{{3.94382289447782*^9, 3.9438229057085066`*^9}, {
  3.943842809935339*^9, 
  3.943842819112769*^9}},ExpressionUUID->"5d25ef04-41cd-49c8-a5b7-\
c26d6780d491"]
},
WindowSize->{1920, 997},
WindowMargins->{{-8, Automatic}, {Automatic, -8}},
FrontEndVersion->"11.2 for Microsoft Windows (64-bit) (September 12, 2017)",
StyleDefinitions->"Default.nb"
]
(* End of Notebook Content *)

(* Internal cache information *)
(*CellTagsOutline
CellTagsIndex->{}
*)
(*CellTagsIndex
CellTagsIndex->{}
*)
(*NotebookFileOutline
Notebook[{
Cell[558, 20, 33022, 964, 1036, "Input",ExpressionUUID->"5d25ef04-41cd-49c8-a5b7-c26d6780d491"]
}
]
*)

